"""Builds the Penpot bundle: the high-fidelity visual design, as one script.

    python3 docs/technical/design/tools/penpot_build.py

Writes `generated/penpot_bundle.js`. Run that file inside the connected Penpot
file — through the MCP plugin's code tool, or Penpot's own plugin console — and
it rebuilds every board from scratch, light and dark.

Why a build step for a design tool at all: the same reason `build.py` exists for
the wireframes. A board tweaked by hand is a board nobody can reproduce, and the
second screen's explorer ends up eight pixels narrower than the first. Penpot's
free plan also keeps only seven days of version history, so the repository — not
the design file — has to be the copy that survives.

Nothing here holds a colour or a chrome dimension of its own. `palette.py` owns
the palette, `kit.py` owns the chrome, and this file only re-emits them as
JavaScript, so the wireframes and the visual design cannot drift apart.
"""

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import kit        # noqa: E402  — layout tokens
import palette    # noqa: E402  — colour roles, both modes

OUT_DIR = os.path.join(HERE, "generated")
SOURCES = ["penpot_kit.js", "penpot_screens.js"]

# ── Layout ───────────────────────────────────────────────────────────────
# The chrome is shared with the wireframes: same product, same panels. The
# window size is NOT — kit.CANVAS_W (1040) is a drawing scale chosen so the
# wireframes stack in review, while the visual design targets the desktop
# window the app actually opens at. Values only defined here are marked.
LAYOUT = {
    "topBar": kit.TOP_BAR,
    "statusBar": kit.STATUS_BAR,
    "explorerW": kit.EXPLORER_W,
    "gitW": kit.GIT_W,
    "pad": kit.PAD,
    "padTight": kit.PAD_TIGHT,
    "row": kit.ROW,
    "listRow": kit.LIST_ROW,
    "windowW": 1440,   # hi-fi only
    "windowH": 900,    # hi-fi only
    "modeBar": 36,     # hi-fi only — the Source/Split/Preview bar
}

# ── Type ─────────────────────────────────────────────────────────────────
# Not shared with kit.py, on purpose: that scale is Excalidraw's hand-drawn
# face at wireframe sizes. This is the product's, and visual-language.md says
# it is decided against real rendered documents rather than against boxes —
# which is what these screens are for.
TYPE = {
    "family": {"sans": "IBM Plex Sans", "mono": "IBM Plex Mono", "serif": "IBM Plex Serif"},
    "brand": 44,        # the wordmark on the empty state
    "headingLg": 24,    # a document's h1/h2 in the preview
    "heading": 17,      # in-document h3
    "bodyRead": 16,     # rendered prose, reading mode
    "bodySplit": 15,    # rendered prose, split view — a narrower measure
    "ui": 13,           # tree rows, buttons, controls
    "code": 12.5,       # the source pane
    "caption": 12,      # tab labels, placeholders, secondary rows
    "label": 10,        # panel captions: EXPLORER, CHANGES, SOURCE
    "status": 11,       # the status bar
}

# ── Reading measure ──────────────────────────────────────────────────────
# A column, not a pane width. Reading mode gets the more generous one because
# about.md is explicit that reading is not a lesser mode.
MEASURE = {"read": 660, "split": 540, "commit": 620}

GRID = {"gapX": 100, "gapY": 120}   # how the boards are laid out for review


def token_block():
    return "const TOKENS = " + json.dumps({
        "light": palette.LIGHT,
        "dark": palette.DARK,
        "layout": LAYOUT,
        "type": TYPE,
        "measure": MEASURE,
        "grid": GRID,
    }, indent=2) + ";\n"


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    parts = [
        "// GENERATED by docs/technical/design/tools/penpot_build.py — do not edit.\n"
        "// Edit penpot_kit.js / penpot_screens.js, or the tokens in palette.py /\n"
        "// kit.py, and rebuild.\n",
        token_block(),
    ]
    for name in SOURCES:
        path = os.path.join(HERE, name)
        parts.append(f"\n// ── {name} " + "─" * (66 - len(name)) + "\n")
        parts.append(open(path, encoding="utf-8").read())
    parts.append("\nawait main();\n")

    out = os.path.join(OUT_DIR, "penpot_bundle.js")
    body = "".join(parts)
    open(out, "w", encoding="utf-8").write(body)
    print(f"{len(body.splitlines()):4d} lines  ->  {out}")


if __name__ == "__main__":
    main()
