/// The document Spike A measures against.
library;

/// Builds a markdown document of at least [lines] lines.
///
/// Generated rather than committed as a fixture, and deterministic rather
/// than random: the numbers this spike reports have to be reproducible on
/// another machine, and a 2000-line file in the repository would be read by
/// nobody and diffed by everybody.
///
/// The shape matters more than the size. A file of one repeated paragraph
/// would flatter any editor: it is the *variety* that costs — headings,
/// fenced code, tables, long unbroken lines, deep lists and inline links are
/// what a syntax highlighter has to keep re-deciding, and they are what real
/// documentation is made of.
String buildMarkdownFixture({required int lines}) {
  final StringBuffer buffer = StringBuffer()
    ..writeln('# Spike A — a document of about $lines lines')
    ..writeln()
    ..writeln(
      'Generated by `markdown_fixture.dart`. Nothing here is real '
      'documentation; the point is the variety of block types.',
    )
    ..writeln();
  int written = 4;
  int section = 0;
  while (written < lines) {
    section++;
    written += _writeSection(buffer, section);
  }
  return buffer.toString();
}

/// Writes one section and answers how many lines it took.
int _writeSection(StringBuffer buffer, int section) {
  buffer
    ..writeln('## Section $section')
    ..writeln()
    ..writeln(_paragraph(section))
    ..writeln()
    ..writeln('### $section.1 A list, because documentation is mostly lists')
    ..writeln();
  for (int item = 1; item <= 4; item++) {
    buffer
      ..writeln('- Item $item — see [the layers](docs/technical/layers.md)')
      ..writeln('  - A nested point that carries an `inline code` span');
  }
  buffer
    ..writeln()
    ..writeln('### $section.2 A fenced block, which highlighting must nest')
    ..writeln()
    ..writeln('```dart')
    ..writeln('Future<Result<GitStatus>> status() async =>')
    ..writeln('    _parsed(await client.status(), statusParser.parse);')
    ..writeln('```')
    ..writeln()
    ..writeln('### $section.3 A table, which is one long line each')
    ..writeln()
    ..writeln('| Field | Type | Notes |')
    ..writeln('|---|---|---|')
    ..writeln('| `root` | path | Absolute path to the folder the user opened |')
    ..writeln('| `repositoryRoot` | path | The enclosing repository |')
    ..writeln()
    ..writeln('> A quote, and then one deliberately long unbroken line that ')
    ..writeln(_longLine(section))
    ..writeln();
  return 27;
}

/// A paragraph with enough inline syntax to keep a highlighter busy.
String _paragraph(int section) =>
    'Paragraph $section holds **bold**, *emphasis*, `code`, a '
    '[link](https://example.com/$section) and a footnote reference[^$section] '
    'so that inline parsing is never trivial. It also runs past eighty '
    'columns on purpose, because real documentation does.';

/// A single line long enough to test horizontal work.
String _longLine(int section) =>
    'A line that never breaks, repeated to length: '
    '${'the quick brown fox jumps over the lazy dog $section. ' * 6}';
